-- AI Case Triage — Supabase / Postgres schema
-- Run in the Supabase SQL Editor before importing the workflows.

-- Vector store for the Knowledge Base (matches the `match_documents` function
-- created by n8n's Supabase vector store template).
create table if not exists kb_documents (
  id         uuid primary key default gen_random_uuid(),
  content    text,
  metadata   jsonb,
  embedding  vector(1536)
);

-- Idempotency: one row per processed case.
create table if not exists processed_cases (
  case_id      text primary key,
  processed_at timestamptz not null default now()
);

-- Audit: one row per triage decision (append-only).
create table if not exists case_triage_audit (
  id          bigint generated by default as identity primary key,
  case_id     text not null,
  category    text,
  priority    text,
  confidence  numeric,
  model       text,
  action      text,          -- 'auto-routed' | 'escalated'
  created_at  timestamptz not null default now()
);

create index if not exists case_triage_audit_case_id_idx
  on case_triage_audit (case_id);

-- Dead-letter: failures captured by the error workflow.
create table if not exists failed_cases (
  id          bigint generated by default as identity primary key,
  case_id     text,
  error       text,
  payload     jsonb,
  created_at  timestamptz not null default now()
);
